apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: lab0-modresort101-modresortapp
  namespace: lab0-modresort-project
  labels:
    app: lab0-modresortapp
spec:
  selector:
    matchExpressions:
    - key: release
      operator: In
      values:
      - lab0-modresort101
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
