apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
name: modresort101-modresortapp
namespace: modresort-project
labels:
  app: modresortapp
  release: modresort101
spec:
  channel: modresort-entitlement/modresort-devchan
  name: ""
  packageFilter:
    version: ">=1.x"
    labelSelector:
      matchLabels:
        package: modresort
        component: main
placement:
  placementRef:
    name: modresortapp101-modresortapp
    kind: PlacementRule
    group: app.ibm.com
overrides:
- clusterName: "/"
  clusterOverrides:
- path: "metadata.namespace"
  value: default