apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: lab0-devchan-modresortchan-deployment
  namespace: lab0-modresort-entitlement
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: lab0-modresortchan
    component: main
    package: lab0-modresort
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: lab0-devchan-modresortchan-deployment
      labels:
        app: lab0-modresortchan
    spec:
      selector:
        matchLabels:
          app: lab0-modresortchan
          release: lab0-modresort-devchan
          tier: frontend
      replicas: 1
      template:
        metadata:
          labels:
            app: lab0-modresortchan
            release: lab0-modresort-devchan
            tier: frontend
        spec:
          containers:
            - name: frontend
              image: "kpostreich/modresort:1.0"
              imagePullPolicy: Always
              ports:
                - containerPort: 9080
              env:
              - name: GET_HOSTS_FROM
                value: dns
              - name: WLP_LOGGING_CONSOLE_FORMAT
                value: json
              - name: WLP_LOGGING_CONSOLE_LOGLEVEL
                value: info
              - name: WLP_LOGGING_CONSOLE_SOURCE
                value: message,trace,accessLog,ffdc
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: lab0-devchan-modresortchan-service
  namespace: lab0-modresort-entitlement
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: lab0-modresortchan
    component: main
    package: lab0-modresort
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: lab0-devchan-modresortchan-service
      labels:
        app: lab0-modresortchan
    spec:
      type: NodePort
      ports:
        - port: 9080
      selector:
        app: lab0-modresortchan
        release: lab0-modresort-devchan
        tier: frontend
